IF EXISTS(SELECT * FROM Sysobjects WHERE type='p' and name='xpBalanceGral')
DROP PROCEDURE xpBalanceGral
GO
CREATE PROCEDURE xpBalanceGral
@empresa	VARCHAR(30),
@periodo	INT,
@ejercicio	INT
AS
BEGIN
	DECLARE @esConsolidado VARCHAR(10)
	
	SET @esConsolidado=@empresa
	
DECLARE @balanza_tbl TABLE (
	TipoCuenta	VARCHAR(20),
	Cuenta		VARCHAR(30),
	Grupo		VARCHAR(250),
	Descripcion	VARCHAR(250),
	CtaDesc		VARCHAR(250),
	Tipo		VARCHAR(20)	NULL
)

INSERT INTO @balanza_tbl
SELECT 'Activo' AS 'TipoCuenta',
Cta.Cuenta,
CASE E2.Descripcion 
		WHEN 'CAJA' THEN 'CIRCULANTE'
		WHEN 'BANCOS E INVERSIONES Y VALORES' THEN 'CIRCULANTE'
		WHEN 'GASTOS PAGADOS POR ANTICIPADO' THEN 'DIFERIDO'
		WHEN 'TERRENO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'EDIFICIO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'ALBERCA' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'MUEBLES Y ENSERES' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'TERRENO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'CONSTRUCCIONES EN PROCESO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'EQUIPO DE FOTOCOPIADO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'EQUIPO DE TRANSPORTE' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'EQUIPO DE COMPUTO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'MAQUINARIA Y EQUIPO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'MONUMENTO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'EQUIPO DE LABORATORIO' THEN 'PROPIEDADES Y EQUIPO'
		WHEN 'DEPRECIACION' THEN 'PROPIEDADES Y EQUIPO'
	ELSE E2.Descripcion
END AS 'Grupo',
dbo.fnJalesBalance(Cta.Cuenta) AS 'Descripcion',
Cta.Descripcion
,CASE E2.Descripcion
	WHEN 'TERRENO' THEN 'APRECIACION'
	WHEN 'EDIFICIO' THEN 'APRECIACION'
	WHEN 'MONUMENTO' THEN 'APRECIACION'
	WHEN 'ALBERCA'	THEN 'APRECIACION'
	WHEN 'MUEBLES Y ENSERES' THEN 'APRECIACION'
	WHEN 'EQUIPO DE COMPUTO' THEN 'APRECIACION'
	WHEN 'MAQUINARIA Y EQUIPO' THEN 'APRECIACION'
	WHEN 'EQUIPO DE LABORATORIO' THEN 'APRECIACION'
	WHEN 'CONSTRUCCIONES EN PROCESO' THEN 'APRECIACION'
	WHEN 'EQUIPO DE FOTOCOPIADO' THEN 'APRECIACION'
	WHEN 'EQUIPO DE TRANSPORTE' THEN 'APRECIACION'
	WHEN 'DEPRECIACION'	THEN 'DEPRECIACION'
END AS 'Tipo'
FROM Cta, Cta E1, Cta E2
WHERE Cta.Rama   = E2.Cuenta
AND E2.Rama    = E1.Cuenta
--AND UPPER(Cta.Tipo) = 'MAYOR'
AND (Cta.Rama = 'B' OR E1.Rama = 'B' OR E2.Rama = 'B')
AND E2.Cuenta NOT IN ('B','C','D','E')
ORDER BY Cta.Cuenta

INSERT INTO @balanza_tbl(TipoCuenta,Cuenta,Grupo,Descripcion,CtaDesc)
SELECT 'Pasivo' AS 'TipoCuenta',
Cta.Cuenta,
CASE E2.Descripcion 
	 WHEN 'BONO DEL CENTENARIO' THEN 'CUENTAS Y DOCUMENTOS POR PAGARAS'
	 WHEN 'IMPUESTO POR PAGAR' THEN 'GASTOS ACUM. Y OTRAS CUENTAS  POR PAGAR'
	 WHEN 'ACREEDORES DIVERSOS' THEN 'GASTOS ACUM. Y OTRAS CUENTAS  POR PAGAR'
	 WHEN 'CUENTAS POR PAGAR' THEN 'GASTOS ACUM. Y OTRAS CUENTAS  POR PAGAR'
	 WHEN 'IMPUESTO POR PAGAR' THEN 'GASTOS ACUM. Y OTRAS CUENTAS  POR PAGAR'
	-- WHEN 'CONTINGENTE' THEN 'GASTOS ACUM. Y OTRAS CUENTAS  POR PAGAR'
	 WHEN 'TRANSPORTE ESCOLAR' THEN 'GASTOS ACUM. Y OTRAS CUENTAS  POR PAGAR'
	 WHEN 'BECAS TRANSPORTE' THEN 'CREDITOS DIFERIDOS'
	 WHEN 'COLEGIATURAS COBRADAS POR ANTICIPADO' THEN 'CREDITOS DIFERIDOS'
   ELSE E2.Descripcion 
END AS 'Grupo',
dbo.fnJalesBalance(Cta.Cuenta) AS 'Descripcion',
Cta.Descripcion
FROM Cta, Cta E1, Cta E2
WHERE Cta.Rama   = E2.Cuenta
AND E2.Rama    = E1.Cuenta
--AND UPPER(Cta.Tipo) = 'MAYOR'
AND (Cta.Rama = 'H' OR E1.Rama = 'H' OR E2.Rama = 'H')
AND E2.Cuenta NOT IN ('H','I','J','K')
ORDER BY Cta.Cuenta

	IF @esConsolidado NOT LIKE 'CON'
	BEGIN
		SELECT at.TipoCuenta,at.Grupo,at.Descripcion,at.Tipo
			  ,SUM(ISNULL(a.Cargos, 0.0)-ISNULL(a.Abonos, 0.0)) AS 'Acumulado'
		FROM @balanza_tbl AS at
		LEFT JOIN Acum AS a ON a.Cuenta = at.Cuenta
		WHERE a.Ejercicio=@ejercicio
		AND a.Periodo=@periodo
		AND a.Empresa=@empresa
		GROUP BY at.TipoCuenta,at.Grupo,at.Descripcion,at.Tipo
	END
	
	IF @esConsolidado LIKE 'CON' 
	BEGIN
		SELECT at.TipoCuenta,at.Grupo,at.Descripcion,at.Tipo
			  ,SUM(ISNULL(a.Cargos, 0.0)-ISNULL(a.Abonos, 0.0)) AS 'Acumulado'
		FROM @balanza_tbl AS at
		LEFT JOIN Acum AS a ON a.Cuenta = at.Cuenta
		WHERE a.Ejercicio=@ejercicio
		AND a.Periodo=@periodo
		GROUP BY at.TipoCuenta,at.Grupo,at.Descripcion,at.Tipo
	END
END

--EXEC xpBalanceGral 'CA',3,2016